### ISSUE TITLE
Missing column in Symbol Pronunciation, Irregular pronunciations

### ISSUE THREAD

**Issue by matthew-piziak** [killercup/scribbles#1]
The _Irregular pronunciations_ table on the [Symbol Pronunciation](https://scribbles.pascalhertleif.de/symbol-pronounciation.html) page is missing the column that actually specifies the irregular pronunciations.

**Comment by killercup** [comment]
Good point. Pretty useless as-is!

I should really update the pronunciation to what http://media.urbit.org/whitepaper.pdf (page 20) says.
