### ISSUE TITLE
arc hub 4k@60Hz

### ISSUE THREAD

**Issue by anton48** [killercup/scribbles#10]
commenting on https://deterministic.space/pascal-vs-usb-c.html: 

"Arc Hub, no Ethernet, but apparently 4k @ 60Hz using Mini DisplayPort. $105 pre-order, ships early 2017"

but actually it is only support 30Hz at 4k no matter HDMI or DP (screenshot from their site below and I bought and tested one).

![arc hub bourge design 2017-08-30 14-16-31](https://user-images.githubusercontent.com/15836314/29870044-4b496312-8d8e-11e7-8278-c8c0dc0ed33c.png)

**Comment by killercup** [comment]
Thank you! I'll update the post ASAP.

Can you use both ports, HDMI and mDP, at the same time? (I'd assume no)

**Comment by anton48** [comment]
system (MacOS itself and switchresx) is able to detect only one display (which was connected first, no matter via DP or HDMI). however, after connecting second monitor we can see an identical copy of desktop on it (in the case of compatible resolutions) or nothing (if resolution for one monitor is not supported on another).

**Comment by killercup** [comment]
Interesting. So apparently one video interface (HDMI 1.4 or DP 1.1 I guess), and two outputs.

Thanks so much for your report! :) I've updated the post.

**Comment by anton48** [comment]
they claimed DP 1.4 and HDMI 1.2 inside and they claimed 4k@60Hz for DP (this is why I bought it actually!) in the past: https://web.archive.org/web/20170606200614/https://www.bourgedesign.com/arc-hub, but I guess that they finally were forced to change spec on the site to 4k@30Hz since there is a bug in the chipset/firmware. more about that here: https://www.jeffgeerling.com/blog/2017/review-arc-hub-usb-c-adapter

quote: "The second lead is with one of the firmware limitations within the chipset that is used to control power distribution among the ports on the hub. We're running tests to see if removing or partially bypassing parts of the firmware is what is needed to achieve 60hz for MacOS users"

moreover, there is a comment from someone who claims that he got 4k@60Hz :) "Works in 60Hz for me, and it is great! I am running a 2016 MacBook Pro with a Dell P2715Q 4K monitor. I am using the AmazonBasics Mini DisplayPort to DisplayPort Cable"

**Comment by killercup** [comment]
Hah, yeah, I could've sworn that page said "60Hz" when I looked at it in January! I think it was on Plugable's blog that I read there were issues with MacBooks and TI chips' DP alternate mode, so I always assumed they had a custom chipset, or at least one that differs from what most others use. Well, apparently, this one doesn't work either… ;)

I'm pretty sure it'd need to use Thunderbolt 3 to really drive those two displays _and_ USB3. And for that it seemed not expensive enough.

**Comment by anton48** [comment]
finally I got a dock which is working at 4k@60Hz just fine: https://www.kensington.com/us/us/4491/k38231ww/sd4600p-usbc-universal-dock-with-power

**Comment by killercup** [comment]
Nice! I'll add it to the post. I assume this is only possible using Thunderbolt 3, even thogh the product page just mentions it's "Thunderbolt™ 3 compatible." 200€ is expensive relative to the 70€ I paid for the i-tech thing I have, but is a bit cheaper than the OWC and Belkin docks.

**Comment by anton48** [comment]
my current notebook has no Thunderbolt :)

**Comment by killercup** [comment]
Huh? What notebook do you have? Can you use the other ports at full speed while using the 4k display over DP? Did you need to install any drivers?

**Comment by anton48** [comment]
this is my notebook: http://www.everymac.com/systems/apple/macbook/specs/macbook-core-m-1.2-12-early-2015-specs.html

I can use eth and usb at the same time with 4k over DP, but not tested the speed (yet). 

it is necessary to install eth driver under mac os.

**Comment by killercup** [comment]
Interesting! Thanks for testing this :)

**Comment by anton48** [comment]
so, it looks that you are right and it is impossible to have 4k@60Hz and USB3.0 at the same time (without additional bandwidth provided by Thunderbolt3). 

when I connect my HDD to the hub first and monitor via DP after that, then 4k@60 resolution is not available or even monitor not detected at all. if I connect monitor via DP first and HDD after that, then HDD detected as USB2.0 :)

![macbook 2017-09-19 14-19-47](https://user-images.githubusercontent.com/15836314/30590234-68bbfe1a-9d46-11e7-9629-7b0f4e802881.png)

![macbook 2017-09-19 14-08-21](https://user-images.githubusercontent.com/15836314/30590235-68bd2470-9d46-11e7-9027-0859506e74d9.png)

**Comment by killercup** [comment]
That makes sense and confirms everything I think I knew about USB-C! :) I'll add your observations to the post.

**Comment by anton48** [comment]
and Kensington sucks too :( https://www.amazon.com/gp/customer-reviews/ROBV0PFXL7RSA/ref=cm_cr_getr_d_rvw_ttl?ie=UTF8&ASIN=B01FMP3B5S
