### ISSUE TITLE
Rich diffs of rendered HTML?

### ISSUE THREAD

**Issue by JZL** [killercup/scribbles#13]
Hi, 
I was looking for exactly what you described in your *Rich diffs of rendered HTML* article and your approach seems very interesting. Do you know if there has been any progress (by you or anyone else)?

Thanks

**Comment by killercup** [comment]
Thanks for your comment! I don't know if any new projects and haven't
written anything myself .:( Did GitHub ever open source their rendering
stack? (They switched to common mark last year so they might've done
something around that time.)

Jonah <notifications@github.com> schrieb am Fr. 26. Jan. 2018 um 00:09:
