### ISSUE TITLE
About your talk @RustFest Rome

### ISSUE THREAD

**Issue by nappa85** [killercup/scribbles#20]
Hello Pascal,
this isn't an issue strictly related to your blog, sorry to take this shortcut to contact you.

On your talk at RustFest in Rome, when talking about using traits to gain more expressive methods sign writing less code, i saw you were using a struct or an enum _Json<T>_ to tell something should become a Serializable struct. I can't find it anywhere, was something you wrote on your own?

On the same talk, I saw a line like _serde_json::from_stream(request.body())_. I know Hyper's Body is a stream, so it makes sense, but I can't find somethin like a "from_stream" method in serde_json, can you point me out this too?

Thank you very much and congratulations for the talk

**Comment by killercup** [comment]
Hey, thanks for reaching out! That part was not using real code, but an "idealized" version of a theoretical framework (so it fits on a slide). You can find the sources of the slides incl. speaker notes [here](https://github.com/killercup/presentation-declarative-programming-in-rust/tree/0a6c033e347f0fc95da0a11e973883a37dfbda4e#generic-type-driven-behavior) (link is to the section on extractors), but the concept is [implemented in actix-web](https://actix.rs/docs/extractors/), as well as described in in [this](https://rust-lang-nursery.github.io/wg-net/2018/10/16/tide-routing.html#extraction) post. I'm not sure how best to parse JSON from a Stream.
