### ISSUE TITLE
Comment: I like your blog layout

### ISSUE THREAD

**Issue by colelawrence** [killercup/scribbles#25]

**Comment by colelawrence** [comment]
Thanks for writing up this post https://deterministic.space/diesel-view-table-trick.html

I really like your blog's layout and design, it reminds me of http://fabiensanglard.net/

I've been meaning to reduce my own to something that straddles code/tech/nerd and actually thoughtful design for awhile now, and I found your layout to be especially appealing.

Cheers

**Comment by killercup** [comment]
Thanks! Glad you like it. Some time ago I extracted it as a Jekyll theme: https://github.com/killercup/jekyll-theme-scribbles

**Comment by colelawrence** [comment]
Thanks for sharing!

Le mer. 20 févr. 2019 à 11:26, Pascal Hertleif <notifications@github.com> a
écrit :
