### ISSUE TITLE
Improve elegant APIs post

### ISSUE THREAD

**Issue by nindalf** [killercup/scribbles#34]
Link - https://deterministic.space/elegant-apis-in-rust.html

Possible improvements

- Remove use of `try!()`. 
- Replace mentions of `error-chain` and `quick-error` with `anyhow` and `thiserror`.

**Comment by killercup** [comment]
Thnaks! I've updated the post a bit, let me know if this addresses all the outdated info you noticed!

**Comment by nindalf** [comment]
One suggestion - replace https://github.com/rust-lang/api-guidelines with https://rust-lang.github.io/api-guidelines/

Same thing, but easier to read.

**Comment by killercup** [comment]
Agreed -- and updated!
