### ISSUE TITLE
Error in a state machine code example

### ISSUE THREAD

**Issue by olivren** [killercup/scribbles#6]
In this [nice write-up](https://scribbles.pascalhertleif.de/elegant-apis-in-rust.html#session-types), the following code example bothers me:

```rust
let package = Package::new(); // -> OpenPackage
package.insert([stuff, padding, padding]); // -> OpenPackage
package.seal_up(); // -> ClosedPackage
// package.insert([more_stuff]); // ERROR: No method `insert` on `ClosedPackage`
package.send(address, postage); // -> DeliveryTracking
```

I don't see how the `package` type could change from one line to another. I think a realistic example would be:

```rust
let package = Package::new(); // -> OpenPackage
let package = package.insert([stuff, padding, padding]); // -> OpenPackage
let package = package.seal_up(); // -> ClosedPackage
// let package = package.insert([more_stuff]); // ERROR: No method `insert` on `ClosedPackage`
let package = package.send(address, postage); // -> DeliveryTracking
```

**Comment by killercup** [comment]
Hey, thanks for your feedback, Oliver! You're right, the code is totally confusing.

I think I'll change it to something like

    let p: OpenPackage = Package::new()
    let p: OpenPackage = package.insert([stuff, padding, padding]);
    let p: ClosedPackage = package.seal_up();

and so on.
