### ISSUE TITLE
slight code error in "Elegant Library APIs"

### ISSUE THREAD

**Issue by ConnyOnny** [killercup/scribbles#7]
At "Take Closures" there is this code example:
```rust
let res: Result<i32, String> = Err("oh noes");
res.unwrap_or(42) // just returns `42`
res.unwrap_or_else(|msg| msg.len() > 12) // will call the closure
```
I think the `> 12` part should be replaced by `as i32`, because the types `i32` and `bool` don't match, making compilation impossible.

**Comment by killercup** [comment]
Thanks! I'll also change `String` to `&str` while I'm at it :)

(I should probably run every code block as a doc test…)
